---
apiVersion: v1
kind: Service
metadata:
  namespace: votingapp
  name: votingapp
  labels:
    part-of: voting-app 
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: votingapp
---
apiVersion: v1
kind: Service
metadata:
  namespace: votingapp
  name: redisdb
  labels:
    part-of: voting-app  
spec:
  ports:
  - port: 6379
  selector:
    app: redisdb